# syntax=buildkit/dockerfile:1

FROM searxng/searxng:latest

COPY settings.yml /etc/searxng/settings.yml
COPY limiter.toml /etc/searxng/limiter.toml

LABEL org.opencontainers.image.source="https://github.com/searxng/searxng-distros"
LABEL org.opencontainers.image.title="SearXNG for Developers"
LABEL org.opencontainers.image.description="SearXNG pre-configured for software developers"

EXPOSE 8080

CMD ["python", "-m", "searx.webapp"]
