#!/usr/bin/env bash
# Regenerate .github/dependabot.yml from discovered distro subdirs.
# Run after adding a new distro to keep dependabot grouped correctly.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEP_FILE="$REPO_ROOT/.github/dependabot.yml"

# Find every directory that contains a Containerfile or .buildah file
DISTROS=()
mapfile -t DISTROS < <(
  find . -mindepth 2 \( -name 'Containerfile' -o -name '*.buildah' \) -print0 | \
    xargs -0 -I{} dirname {} | \
    sed 's|^\./||' | \
    sort -u
)

{
  cat <<'HEADER'
# Auto-generated by scripts/regenerate-dependabot.sh — do not edit by hand.
# Regenerate after adding a new distro:  ./scripts/regenerate-dependabot.sh
version: 2
updates:

  # ── GitHub Actions (root) ──────────────────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  # ── Distro subdirs ─────────────────────────────────────────────────
HEADER

  for dir in ${DISTROS[@]+"${DISTROS[@]}"}; do
    # Use the dirname as the group name (replace / with -)
    group_name="${dir//\//-}"
    cat <<ENTRY

  - package-ecosystem: "docker"
    directory: "/${dir}"
    schedule:
      interval: "weekly"
    groups:
      ${group_name}-distro:
        patterns: ["*"]
ENTRY
  done

} > "$DEP_FILE"

count=${#DISTROS[@]}
if [ "$count" -gt 0 ]; then
  echo "Regenerated $DEP_FILE — $count distro(s) discovered: ${DISTROS[*]}"
else
  echo "Regenerated $DEP_FILE — no distros found (add Containerfiles to subdirs)"
fi
